# Generated by Django 3.0.5 on 2020-04-27 09:58

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion

from django.contrib.postgres.operations import CreateExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        #CreateExtension('postgis'),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Language name')),
                ('region', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Approximate language distribution region(s)')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_eng', models.CharField(max_length=200, null=True, verbose_name='English name')),
                ('place_type', models.CharField(default='unknown', max_length=200, verbose_name='Type of place')),
                ('location', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Physical location')),
                ('desc', models.CharField(max_length=500, null=True, verbose_name='Description')),
                ('source', models.CharField(default='unknown', max_length=200, verbose_name='Data source')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Additional data')),
                ('lang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='featuremap.Language')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='featuremap.Place')),
            ],
        ),
    ]
