# Generated by Django 3.0.5 on 2020-04-29 02:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featuremap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is location public'),
        ),
        migrations.AlterField(
            model_name='place',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='', verbose_name='Additional data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='desc',
            field=models.CharField(default='', max_length=500, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='name_eng',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='English name'),
            preserve_default=False,
        ),
    ]
