# Generated by Django 3.0.5 on 2020-05-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featuremap', '0004_auto_20200506_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lang',
            field=models.CharField(blank=True, default='unknown', max_length=200, verbose_name='Language'),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
